border_tracker_app/urls.py
from django.urls import path
from .views import *

app_name = "border_tracker_app"

urlpatterns = [
    path('history', BorderCrossingHistoryPage.as_view(), name='border-crossing-history-page'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include

from authapp.views import IndexPage

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', IndexPage.as_view(), name='index'),
    path('travel-documents/', include('travel_doc_tracker_app.urls', namespace='travel_doc_tracker')),
    path('border-crossing/', include('border_tracker_app.urls', namespace='border_crossing_tracker')),
    path('residence-permit/', include('residence_permit_tracker_app.urls', namespace='residence_permit_tracker')),
]

residence_permit_tracker_app/urls.py
from django.urls import path
from .views import *

app_name = "residence_permit_tracker_app"

urlpatterns = [
    path('process-history/', ResidencePermitProcessHistoryPage.as_view(),
         name='residence-permit-process-history-page'),
    path('single-process/<int:pk>', SinglePermitUpdateWidget.as_view(),
         name='single-residence-permit-process-form-widget'),
    path('process-history-record/create/', SinglePermitHistoryRecordCreatePage.as_view(),
         name='residence-permit-process-history-record-create-form-page'),
    path('process-history-record/<int:pk>/update/', SinglePermitHistoryRecordUpdatePage.as_view(),
         name='residence-permit-process-history-record-update-form-page'),
    path('process-history-record/<int:pk>/delete/', SinglePermitHistoryRecordDeleteView.as_view(),
         name='residence-permit-process-history-record-delete'),
]

travel_doc_tracker_app/urls.py
from django.urls import path
from .views import *

app_name = "travel_doc_tracker_app"

urlpatterns = [
    path('expiry-tracker/', DocumentTrackerPage.as_view(), name='document-expiry-tracker-page'),
    path('single-document/<int:pk>', DocumentUpdateFormWidget.as_view(), name='single-document-update-form'),
]

templates/base/base.html
<!DOCTYPE html>
<html lang="en">
{% block loads %}
{% endblock %}
<head>
    <meta charset="UTF-8">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    {% block materialize_stylesheets %}
    {% endblock %}
    {% block extra_stylesheets %}
    {% endblock %}
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>
        {% block title_content %}
            {{ title|default:'Materialize Base Template' }}
        {% endblock %}
    </title>
</head>
<body>
    {% block content %}
    {% endblock %}
    {% block materialize_javascripts %}
    {% endblock %}
    {% block extra_javascripts %}
    {% endblock %}
</body>
</html>

templates/base/materialize_base.html
{% extends 'base/base.html' %}

{% block loads %}
    {% load static %}
{% endblock %}

{% block materialize_stylesheets %}
    <link type="text/css" rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css"  media="screen,projection"/>
{% endblock %}

{% block materialize_javascripts %}
    <script type="text/javascript" src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
{% endblock %}

templates/base/page.html
{% extends 'base/materialize_base.html' %}

{% block content %}

<div class="navbar-fixed">
    <nav>
        <div class="nav-wrapper blue darken-1">
            <div class="container">
                <a href="{% url 'index' %}" class="brand-logo">E-Migrant</a>
                <ul id="nav-mobile" class="right hide-on-med-and-down">
                    <li><a href="/">Dashboard</a></li>
                    <li><a href="{% url 'travel_doc_tracker:document-expiry-tracker-page' %}">Travel documents</a></li>
                    <li><a href="{% url 'residence_permit_tracker:residence-permit-process-history-page' %}">Residence card</a></li>
                    <li><a href="{% url 'border_crossing_tracker:border-crossing-history-page' %}">Borders tracking</a></li>
                    <li><a href="{% url 'index' %}" class="waves-effect waves-light blue btn">Sign in</a></li>
                    <li><a href="{% url 'index' %}" class="waves-effect waves-light btn">Register</a></li>
                </ul>
            </div>
        </div>
    </nav>
</div>

<!-- Content goes here-->
<div class="grey lighten-3">
    <div class="container" style="min-height:70vh;">
        {% block page_body_content %}
        {% endblock %}
    </div>
</div>

<!-- END page body -->
<!-- Footer -->

<footer class="page-footer blue darken-1">
    <div class="container">
        <div class="row">
            <div class="col l6 s12">
                <h5 class="white-text">Footer Content</h5>
                <p class="grey-text text-lighten-4">You can use rows and columns here to organize your footer
                    content.</p>
            </div>
            <div class="col l4 offset-l2 s12">
                <h5 class="white-text">Links</h5>
                <ul>
                    <li><a class="grey-text text-lighten-3" href="#!">Link 1</a></li>
                    <li><a class="grey-text text-lighten-3" href="#!">Link 2</a></li>
                    <li><a class="grey-text text-lighten-3" href="#!">Link 3</a></li>
                    <li><a class="grey-text text-lighten-3" href="#!">Link 4</a></li>
                </ul>
            </div>
        </div>
    </div>
    <div class="footer-copyright">
        <div class="container">
            © 2019 Copyright Text
            <a class="grey-text text-lighten-4 right" href="#!">More Links</a>
        </div>
    </div>
</footer>


{% endblock %}
{% block extra_javascripts %}
<script>
$(document).ready(function(){
    $('.sidenav').sidenav();
});
</script>
{% endblock %}