project/urls.py
from django.contrib import admin
from django.urls import path, include

from authapp.views import IndexPage

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', IndexPage.as_view(), name='index'),
    path('travel-documents/', include('travel_doc_tracker_app.urls', namespace='travel_doc_tracker')),
    path('border-crossing/', include('border_tracker_app.urls', namespace='border_crossing_tracker')),
    path('residence-permit/', include('residence_permit_tracker_app.urls', namespace='residence_permit_tracker')),
]

residence_permit_tracker_app/urls.py
from django.urls import path
from .views import *

app_name = "residence_permit_tracker_app"

urlpatterns = [
    path('process-history/', ResidencePermitProcessHistoryPage.as_view(),
         name='residence-permit-process-history-page'),
    path('single-process/<int:pk>', SinglePermitUpdateWidget.as_view(),
         name='single-residence-permit-process-form-widget'),
    path('process-history-record/create/', SinglePermitHistoryRecordCreatePage.as_view(),
         name='residence-permit-process-history-record-create-form-page'),
    path('process-history-record/<int:pk>/update/', SinglePermitHistoryRecordUpdatePage.as_view(),
         name='residence-permit-process-history-record-update-form-page'),
    path('process-history-record/<int:pk>/delete/', SinglePermitHistoryRecordDeleteView.as_view(),
         name='residence-permit-process-history-record-delete'),
]

residence_permit_tracker_app/models.py
from django.contrib.auth.models import User
from django.db import models


class ResidencePermitType(models.Model):
    name = models.CharField(max_length=32, unique=True)

    def __str__(self):
        return self.name


class ResidencePermitStatus(models.Model):
    name = models.CharField(max_length=32, unique=True)

    def __str__(self):
        return self.name


class ResidencePermitProcess(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    permit_type = models.ForeignKey(ResidencePermitType, on_delete=models.CASCADE,
                                    null=True)
    estimated_issue_date = models.DateField(null=True, blank=True)
    status = models.ForeignKey(ResidencePermitStatus, on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username


class ProcessActivityType(models.Model):
    name = models.CharField(max_length=32, unique=True)

    def __str__(self):
        return self.name


class ResidencePermitProcessHistory(models.Model):
    residence_permit_process = models.ForeignKey(ResidencePermitProcess, on_delete=models.CASCADE)
    date = models.DateField()
    activity_type = models.ForeignKey(ProcessActivityType, on_delete=models.CASCADE)
    details = models.CharField(max_length=240)

    def __str__(self):
        return f"{self.date} - {self.activity_type}"

residence_permit_tracker_app/forms.py
from django import forms

from residence_permit_tracker_app.models import ResidencePermitProcessHistory


class ResidencePermitProcessHistoryRecordCreateForm(forms.ModelForm):
    class Meta:
        model = ResidencePermitProcessHistory
        fields = ['residence_permit_process', 'date', 'activity_type', 'details']
        widgets = {'residence_permit_process': forms.HiddenInput()}

residence_permit_tracker_app/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import UpdateView, ListView, CreateView, DeleteView

from residence_permit_tracker_app.forms import ResidencePermitProcessHistoryRecordCreateForm
from residence_permit_tracker_app.models import ResidencePermitProcess, ResidencePermitProcessHistory
from residence_permit_tracker_app.services.residence_permit_process import ResidencePermitProcessCase


class ResidencePermitProcessHistoryPage(LoginRequiredMixin, ListView):
    template_name = 'residence_permit_tracker_app/process_history_page.html'
    http_method_names = ['get']
    model = ResidencePermitProcess
    context_object_name = 'permits'

    def get_queryset(self, **kwargs):
        return ResidencePermitProcessCase.get_residence_permit_processes(user=self.request.user)


class SinglePermitUpdateWidget(LoginRequiredMixin, UpdateView):
    template_name = 'residence_permit_tracker_app/single_permit_widget.html'
    http_method_names = ['get', 'post']
    model = ResidencePermitProcess
    fields = ['permit_type', 'estimated_issue_date', 'status']

    def get_queryset(self, **kwargs):
        return ResidencePermitProcessCase.get_residence_permit_processes(user=self.request.user)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['permit_number'] = self.object.pk
        context['statuses'] = ResidencePermitProcessHistory.objects.filter(
            residence_permit_process=self.object).order_by('date')
        return context

    def get_success_url(self, **kwargs):
        return reverse_lazy("residence_permit_tracker:single-residence-permit-process-form-widget",
                            kwargs={'pk': int(self.kwargs.get('pk'))})


class SinglePermitHistoryRecordCreatePage(LoginRequiredMixin, CreateView):
    template_name = 'residence_permit_tracker_app/single_permit_history_record_create_page.html'
    http_method_names = ['get', 'post']
    form_class = ResidencePermitProcessHistoryRecordCreateForm

    def get_initial(self):
        """
        Returns the initial data to use for forms on this view.
        """
        initial = super().get_initial()
        initial['residence_permit_process'] = ResidencePermitProcess.objects.filter(
            user=self.request.user,
        ).first()
        return initial

    def form_valid(self, form):
        # TODO: Rebuild the lookup for multiple processes
        form.residence_permit_process = ResidencePermitProcess.objects.filter(
            user=self.request.user,
        ).first()
        self.object = form.save()
        return super().form_valid(form)

    def get_success_url(self, **kwargs):
        return reverse_lazy("residence_permit_tracker:residence-permit-process-history-page")


class SinglePermitHistoryRecordUpdatePage(LoginRequiredMixin, UpdateView):
    template_name = 'residence_permit_tracker_app/single_permit_history_record_update_page.html'
    http_method_names = ['get', 'post']
    model = ResidencePermitProcessHistory
    fields = ['date', 'activity_type', 'details']

    def get_queryset(self, **kwargs):
        return ResidencePermitProcessHistory.objects.filter(residence_permit_process__user=self.request.user)

    def get_success_url(self, **kwargs):
        return reverse_lazy("residence_permit_tracker:residence-permit-process-history-page")


class SinglePermitHistoryRecordDeleteView(LoginRequiredMixin, DeleteView):
    http_method_names = ['post']

    def get_queryset(self, **kwargs):
        return ResidencePermitProcessHistory.objects.filter(residence_permit_process__user=self.request.user)

    def get_success_url(self, **kwargs):
        return reverse_lazy("residence_permit_tracker:residence-permit-process-history-page")

residence_permit_tracker_app/templates/residence_permit_tracker_app/process_history_page.html
{% extends 'base/page.html' %}
{% block page_body_content %}

<div class="row">
    <div class="col s12 m12">
        <div class="card-panel white">
            <h5 class="black-text">Residence permit issuing process tracking</h5>
            <h6 class="black-text">Here You can fill in all the details of issuing process, so we will remind You about
                issuing date. In case of negative answer You will have full process history.</h6>
        </div>
    </div>
</div>

<div id="card-list">
</div>
{% endblock %}

{% block extra_javascripts %}
{{ block.super }}
<script>
$(document).ready(function(){
    {% for permit in permits %}
        $.ajax({url: "{% url 'residence_permit_tracker:single-residence-permit-process-form-widget' pk=permit.pk %}",
            success: function(result){
                $("#card-list").html(result);
        }});
    {% endfor %}
});
</script>
<script>
function submitResidenceForm(formNumber, csrfToken) {
    $.ajax({
        headers: { "X-CSRFToken": csrfToken },
        type: "POST",
        url: $("#permit-process-form-" + formNumber).attr("action"),
        dataType: "html",
        data: $("#permit-process-form-" + formNumber).serialize(),
    })
    .done(function(data){
        $("#document" + formNumber).html(data);
    })
};
</script>
<script>
    $(document).on('click', '[id^="submit-form-"]', function() {
        submitResidenceForm(this.id.slice(-1), $(this).parents("form").find('input[name="csrfmiddlewaretoken"]').val())
    });
</script>
{% endblock %}

residence_permit_tracker_app/templates/residence_permit_tracker_app/single_permit_history_record_create_page.html
{% extends 'base/page.html' %}
{% load widget_tweaks %}

{% block page_body_content %}
<div class="row">
    <div class="col s12 m12">
        <div class="card-panel white">
            <h5 class="black-text">Residence permit issuing process tracking</h5>
            <h6 class="black-text">Here You can fill in all the details of issuing process, so we will remind You about
                issuing date. In case of negative answer You will have full process history.</h6>
        </div>
    </div>
</div>
<div id="card-list">
    <form method="post" id="permit-process-history-record-create"
          action="{% url 'residence_permit_tracker:residence-permit-process-history-record-create-form-page'%}">
        {% csrf_token %}
        <div class="card-panel white">
            <div class="row">
            <div class="col s12 offset-m1">
                <h5 class="black-text">History record create</h5>
            </div>
        </div>
            <div class="row">
                <div class="col s12">
                    {{ form.residence_permit_process }}
                    <div class="input-field col s12 m3">
                        {% if form.date.errors %}
                        <label class="active red-text">{{ form.date.errors.0 }}</label>
                        {% render_field form.date class="datepicker invalid" %}
                        {% else%}
                        <label class="{% if form.date.value %}active{% endif %}">{{ form.date.label
                            }}</label>
                        {% render_field form.date class="datepicker" %}
                        {% endif %}
                    </div>
                    <div class="input-field col s12 m3">
                        {% if form.activity_type.errors %}
                        <label class="active red-text">{{ form.activity_type.errors }}</label>
                        {{ form.activity_type }}
                        {% else%}
                        <label class="active">{{ form.activity_type.label }}</label>
                        {{ form.activity_type }}
                        {% endif %}
                    </div>
                    <div class="input-field col s12 m6">
                        {% if form.details.errors %}
                        <label class="active red-text">{{ form.details.errors }}</label>
                        {{ form.details }}
                        {% else%}
                        <label class="active">{{ form.details.label }}</label>
                        {{ form.details }}
                        {% endif %}
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col s12">
                    <div class="col s12">
                        <button class="waves-effect waves-light btn blue darken-1 right" type="submit"><i
                                class="material-icons left">save</i><strong>Save</strong><</button>
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>
{% endblock %}

{% block extra_javascripts %}
{{ block.super }}
<script>
    $('select').formSelect();
    $('.datepicker').datepicker({
  format: "yyyy-mm-dd"
});
</script>
{% endblock %}

residence_permit_tracker_app/templates/residence_permit_tracker_app/single_permit_history_record_update_page.html
{% extends 'base/page.html' %}
{% load widget_tweaks %}

{% block page_body_content %}
<div class="row">
    <div class="col s12 m12">
        <div class="card-panel white">
            <h5 class="black-text">Residence permit issuing process tracking</h5>
            <h6 class="black-text">Here You can fill in all the details of issuing process, so we will remind You about
                issuing date. In case of negative answer You will have full process history.</h6>
        </div>
    </div>
</div>
<div id="card-list">
    <form method="post" id="permit-process-history-record-update"
          action="{% url 'residence_permit_tracker:residence-permit-process-history-record-update-form-page' pk=view.kwargs.pk  %}">
        {% csrf_token %}
        <div class="card-panel white">
            <div class="row">
            <div class="col s12 offset-m1">
                <h5 class="black-text">History record update</h5>
            </div>
        </div>
            <div class="row">
                <div class="col s12">
                    <div class="input-field col s12 m3">
                        {% if form.date.errors %}
                        <label class="active red-text">{{ form.date.errors.0 }}</label>
                        {% render_field form.date class="datepicker invalid" %}
                        {% else%}
                        <label class="{% if form.date.value %}active{% endif %}">{{ form.date.label
                            }}</label>
                        {% render_field form.date class="datepicker" %}
                        {% endif %}
                    </div>
                    <div class="input-field col s12 m3">
                        {% if form.activity_type.errors %}
                        <label class="active red-text">{{ form.activity_type.errors }}</label>
                        {{ form.activity_type }}
                        {% else%}
                        <label class="active">{{ form.activity_type.label }}</label>
                        {{ form.activity_type }}
                        {% endif %}
                    </div>
                    <div class="input-field col s12 m6">
                        {% if form.details.errors %}
                        <label class="active red-text">{{ form.details.errors }}</label>
                        {{ form.details }}
                        {% else%}
                        <label class="active">{{ form.details.label }}</label>
                        {{ form.details }}
                        {% endif %}
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col s12">
                    <div class="col s12">
                        <button class="waves-effect waves-light btn blue darken-1 right" type="submit"><i
                                class="material-icons left">save</i><strong>Save</strong><</button>
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>
{% endblock %}

{% block extra_javascripts %}
{{ block.super }}
<script>
    $('select').formSelect();
    $('.datepicker').datepicker({
  format: "yyyy-mm-dd"
});
</script>
{% endblock %}

residence_permit_tracker_app/templates/residence_permit_tracker_app/single_permit_widget.html
{% load widget_tweaks %}
<div class="row">
    <div class="col s12 m12">
        <div class="card-panel white">
            <div class="row">
                <div class="col s12">
                    <h5 class="black-text">Residence permit 1</h5>
                </div>
            </div>
            <div class="row">
                <div class="col s12">
                    <form method="post" id="permit-process-form-{{ permit_number }}"
                          action="{% url 'residence_permit_tracker_app:single-residence-permit-process-form-widget' pk=permit_number %}">
                        {% csrf_token %}
                        <div class="input-field col s12 m3">
                            {% if form.permit_type.errors %}
                            <label class="active red-text">{{ form.permit_type.errors }}</label>
                            {% else%}
                            <label class="active">{{ form.permit_type.label }}</label>
                            {% endif %}
                            {{ form.permit_type }}
                        </div>
                        <div class="input-field col s12 m3">
                            {% if form.status.errors %}
                            <label class="active red-text">{{ form.status.errors }}</label>
                            {% else%}
                            <label class="active">{{ form.status.label }}</label>
                            {% endif %}
                            {{ form.status }}
                        </div>
                        <div class="input-field col s12 m3">
                            {% if form.estimated_issue_date.errors %}
                            <label class="active red-text">{{ form.estimated_issue_date.errors.0 }}</label>
                            {% render_field form.estimated_issue_date class="datepicker invalid" %}
                            {% else%}
                            <label class="{% if form.estimated_issue_date.value %}active{% endif %}">{{
                                form.estimated_issue_date.label }}</label>
                            {% render_field form.estimated_issue_date class="datepicker" %}
                            {% endif %}
                        </div>
                        <div class="input-field col s12 m3">
                            <a class="waves-effect waves-light btn blue darken-1"
                               id="submit-form-{{ permit_number }}"><i
                                    class="material-icons left">save</i><strong>Save</strong></a>
                        </div>
                    </form>
                </div>
            </div>
            <div class="row">
                <div class="col s12">
                    <table class="highlight responsive-table">
                        <thead>
                        <tr>
                            <th style="width: 25%">Date</th>
                            <th style="width: 40%">Action</th>
                            <th style="width: 35%">Details</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for status in statuses %}
                        <tr>

                            <td style="width: 25%">{{ status.date }}</td>
                            <td style="width: 40%">{{ status.activity_type }}</td>
                            <td style="width: 35%">
                                <form method="post" id="permit-process-record-remove-{{ permit_number }}"
                                      action="{% url 'residence_permit_tracker_app:residence-permit-process-history-record-delete' pk=status.pk %}">
                                    {% csrf_token %}
                                    {{ status.details }}
                                    <button id="delete-record-{{ status.pk }}"
                                            style="background:none!important;
                                                   border:none;
                                                   padding:0!important;
                                                   cursor: pointer;"
                                            type="submit"
                                            class="right col m2"><i class="material-icons blue-text">delete</i></button>
                                    <a href="{% url 'residence_permit_tracker:residence-permit-process-history-record-update-form-page' pk=status.pk  %}"><i
                                            class="material-icons right col m1">edit</i></a>
                                </form>

                            </td>

                        </tr>
                        {% empty %}
                        <tr>
                            <td style="width: 25%">None</td>
                            <td style="width: 40%">None</td>
                            <td style="width: 35%">None</td>
                            >
                        </tr>
                        {% endfor %}

                        </tbody>
                    </table>
                </div>
            </div>
            <div class="row">
                <div class="col s12">
                    <div class="col s12">
                        <a href="{% url 'residence_permit_tracker:residence-permit-process-history-record-create-form-page' %}"
                           class="waves-effect waves-light btn blue darken-1 right"><i
                                class="material-icons left">add</i><strong>Add new record</strong></a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script>
    $('select').formSelect();
    $('.datepicker').datepicker({
  format: "yyyy-mm-dd"
});








</script>